name: CSS Check
on:
  push:
  pull_request:
    branches:
      - main
  
jobs:
  testingCSS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Requried will all actions
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.0.0
      with:
        root: source/css/
        css: true
